# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: aaact-aatia/newsletter-bulletin
  branch: main
  identity_url: https://auth.decapbridge.com/sites/eda45ea5-0b8d-44f2-bc1e-5a7a4589443b
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://aaact.canada.ca/newsletters

publish_mode: editorial_workflow

media_folder: "public/uploads"
public_folder: "/uploads"

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: "newsletters"
    label: "Newsletters"
    folder: "content/newsletters"
    create: true
    slug: "{{slug}}"
    i18n: true
    format: "frontmatter"
    fields:
      - { label: "Title (required)", name: "title", widget: "string", i18n: true }
      - { label: "Other language title (required)", name: "otherLanguageTitle", widget: "string", i18n: true }
      - { label: "Description (required)", name: "description", widget: "markdown", i18n: true }
      - { label: "Permalink (full path)", name: "permalink", required: false, widget: "string", i18n: true }
      - { label: "Permalink to other language (full path)", name: "otherLanguagePermalink", required: false, widget: "string", i18n: true }
      - { label: "Details (required)", name: "body", widget: "markdown",  i18n: true }
